package main

import (
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
)

// Static projection: a static web server serves exactly one directory, while a
// deployment keeps its files in several. Publishing is therefore a projection:
//
//	<publish>/            rendered pages — render/ hoisted to the root
//	<publish>/assets/     stylesheets, scripts, icons, media
//	<publish>/static/     uploads and stickers
//	<publish>/error/      standalone error pages, from render/error/
//	<publish>/robots.txt  generated, see below
//	<publish>/feed.xml    generated, see below
//	<publish>/sitemap.xml generated, see below
//
// Two of these are engine files a site may override, so the projection resolves the
// deployment's copy over the engine's — the same rule the running server applies. A
// site is not expected to carry a copy of the engine's stylesheets; without this the
// published tree would ship an unstyled site, because the deployment directory holds
// only what the site chose to change.
//
// config/ and state/ are deliberately absent: config/site.json holds the admin password,
// state/ the event log, and everything under the published root is fetchable by URL — a
// deployment that put either there would serve /config/site.json to anyone who asked.
//
// The tree is derived: every projection wipes and rebuilds it, so deleting it is
// always safe and never loses anything that cannot be regenerated.

const publishMarker = ".projection"

const publishMarkerNote = "Generated by `silphuu -project-static`. Derived tree — safe to delete, never edit."

// projectionSources maps a directory in the deployment to its place in the published
// tree. An empty destination means the root itself, and a later entry overwrites an
// earlier one at the same path.
//
// layered marks the directories the engine also ships: the engine's copy is laid down
// first and the deployment's on top, file by file. render/ is runtime output with no
// meaningful engine side, so it is not layered — overlaying the engine's render cache
// would publish the engine's demo pages into a real site.
//
// public/ comes last because it holds the site's own root-level files — the favicon, and
// anything else the site wants served at /. Nothing else may be allowed to overwrite it.
var projectionSources = []struct {
	from    string
	to      string
	layered bool
}{
	{"render", "", false},
	{"public", "", true},
	{"assets", "assets", true},
	{"static", "static", true},
}

// projectionSkip are names that must never reach a published tree: the render cache's
// own bookkeeping, and the OS artefacts that ride along in a working copy.
var projectionSkip = map[string]bool{
	".render-inputs": true,
	".DS_Store":      true,
}

// projectStaticTree rebuilds the published tree at dst from the deployment's own
// directories.
//
// It refuses to touch a directory it did not create: dst must be absent, or carry the
// marker a previous projection left. Wiping is only safe for a tree this function
// generated, and pointing the destination at the wrong path must not delete anything.
func projectStaticTree(dst string) error {
	if dst == "" {
		return errors.New("projection destination is empty")
	}
	if _, err := os.Stat(dst); err == nil {
		if _, err := os.Stat(filepath.Join(dst, publishMarker)); err != nil {
			return fmt.Errorf("%s already exists and was not produced by a projection; refusing to touch it", dst)
		}
	}
	if err := os.RemoveAll(dst); err != nil {
		return fmt.Errorf("clear %s: %w", dst, err)
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return err
	}

	for _, s := range projectionSources {
		// Engine first, deployment second: later copies overwrite earlier ones, which is
		// what makes the deployment's file win.
		var roots []string
		if s.layered {
			roots = append(roots, filepath.Join(engineRoot, s.from))
		}
		roots = append(roots, filepath.Join(homeRoot, s.from))

		last := ""
		for _, from := range roots {
			from = filepath.Clean(from)
			if from == last { // default layout: engine and deployment are the same tree
				continue
			}
			last = from
			if _, err := os.Stat(from); err != nil {
				if os.IsNotExist(err) {
					continue
				}
				return err
			}
			if err := projectTree(from, filepath.Join(dst, s.to)); err != nil {
				return fmt.Errorf("project %s: %w", s.from, err)
			}
		}
	}

	// Generated rather than copied: the handlers build these from the post set and the site's
	// own base URL, and the engine's static copies name a placeholder host. A published tree
	// has no handler behind it, so each one has to exist as a file. Serving the same bytes
	// either way is the point of a projection.
	base := siteBaseURL()
	for _, f := range []struct{ name, body string }{
		{"robots.txt", robotsTxt(base)},
		{"feed.xml", feedXML(base)},
		{"sitemap.xml", sitemapXML(base)},
	} {
		if err := os.WriteFile(filepath.Join(dst, f.name), []byte(f.body), 0o644); err != nil {
			return err
		}
	}

	return os.WriteFile(filepath.Join(dst, publishMarker), []byte(publishMarkerNote+"\n"), 0o644)
}

// projectTree copies src into dst, skipping projectionSkip.
//
// Symlinks are followed. The result is served by a web server, so it has to be
// self-contained — a link pointing outside the tree would either break or escape the
// served root. (The engine's error images are links to a shared file, so this is the
// common case, not a corner one.)
func projectTree(src, dst string) error {
	return filepath.WalkDir(src, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if projectionSkip[d.Name()] {
			if d.IsDir() {
				return fs.SkipDir
			}
			return nil
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)

		if d.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		info, err := os.Stat(path) // follows a symlink
		if err != nil {
			return err
		}
		if info.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		return copyFile(path, target)
	})
}

// copyFile copies one regular file, creating its parent directory.
func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		return err
	}
	return out.Close()
}
